### ISSUE TITLE
Default parameters likelihood.data VS input.param

### ISSUE THREAD

**Issue by paganol** [brinckmann/montepython_public#173] opened 2020-12-01 16:39 UTC
Hi there,
since the last version, we see a strange behavior in how the code handles the input parameters for a generic likelihood. 
In a few words, when we modify the default parameters of a likelihood in the input.param the code still uses the parameters contained in the likelihood.data file. This seems to be in contrast with what is stated in [likelihood_class.py](https://github.com/brinckmann/montepython_public/blob/e2a8af41725ce31d63718eafe7ec614801b291f6/montepython/likelihood_class.py#L133) line 133. 
This is with montepython v3.3.0 and python 3.6.4 
Last time we checked with v3.1.0 and python 2.7.12  the settings in the input.param were overwriting the defaults

**Comment by brinckmann** [comment] 2020-12-01 19:47
Hi Luca,

It would seem to me the behavior depends on how individual likelihoods handle the flags. E.g. the 'non_linear' setting is often overwritten by some likelihoods that require the setting, so what is set in the param file becomes irrelevant.

Patch 2.0.2 was before my time working on the code, so I'm not exactly sure how that feature was intended to work. I can't see how changes from 3.1 to 3.3 could have affected it, so I'm a bit stumped. However, @schoeneberg added a patch on the private repository that should streamline using the param file to set likelihood parameters. I haven't tested it, but I can push that to public in the next days so you can try it out.

Best,
Thejs

**Comment by paganol** [comment] 2020-12-01 20:40
Hi Thejs,
thanks for the quick answer.
Yeah, agree, I was puzzled by that too. The code is the same. I can tell you what I'm trying to do, in case it helps. 
I'm running a generic likelihood module, and I want to change some default settings, like in fake_planck_bluebook change f_sky or l_max. Really just that, not even some theory related parameters. 
In the past with 3.1 and python 2, setting that in the input.param was enough, the new parameters were used by the likelihood module replacing the defaults. Now, in a similar situation, with 3.3 and python 3, it seems that the default parameters get priority wrt the ones set in the input.param file, which is kind of weird to me. 
I agree with you that the code basically didn't change between 3.1 and 3.3, at least in that part. The only thing I can advocate is some behavior of the functions used, that has changed between python 2 and 3, which, I admit, seems pretty unlikely.
Thanks for looking into this
cheers
Luca

**Comment by brinckmann** [comment] 2020-12-01 20:44
Thanks for additional information! Indeed it must be related to python 2 vs python 3, since this whole segment was coded for python 2 and updated to python 3 something obviously went wrong. I'll check out the patch by Nils and push it to public when I have a chance, that should work for python 3.

Best,
Thejs

**Comment by schoeneberg** [comment] 2020-12-10 19:44
Hey all,

indeed this is an issue that I have encountered myself before, and I have written a fix for it. It should be included in a private branch of mine, so when @brinckmann includes it, the issue should be fixed. Since I thought that changing the parameters of a likelihood from the input.param file is a very valuable asset, I programmed a version where it should be included.

If I recall correctly, the behavior is even a bit more strange @paganol : In my case, the code usually used the parameter from the log.param preferentially for the run compared to the input.param file. However, for the first run there is no log.param. This meant, that the first run would often be executed with different parameters than the second or subsequent runs. In the newer version this should not be the case anymore.

Please update us if this issue is resolved!

Cheers!

**Closed** 2023-02-03 12:56 UTC
