### ISSUE TITLE
MontePython.py run (or info) -h doesn't work

### ISSUE THREAD

**Issue by talabadi** [brinckmann/montepython_public#140] opened 2020-07-07 17:13 UTC
I followed the instructions (using Linux Mint) but when I tried to run "python montepython/MontePython.py run -h" (or info -h) I get:

TypeError: unicode argument expected, got 'str'

Any idea what is wrong? Does it mean that Monte Python will not work correctly?

the error is preceded by:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/groot/codes/montepython_public-3.3/montepython/run.py", line 32, in run
    custom_command)
  File "/home/groot/codes/montepython_public-3.3/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/groot/codes/montepython_public-3.3/montepython/initialise.py", line 31, in initialise
    command_line = parser_mp.parse(custom_command)
  File "/home/groot/codes/montepython_public-3.3/montepython/parser_mp.py", line 1050, in parse
    args = parser.safe_parse_args()
  File "/home/groot/codes/montepython_public-3.3/montepython/parser_mp.py", line 47, in safe_parse_args
    return self.parse_args(args)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1925, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1902, in consume_positionals
    take_action(action, args)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1811, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1100, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1943, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1883, in consume_optional
    take_action(action, args, option_string)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 1811, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/groot/codes/montepython_public-3.3/montepython/parser_mp.py", line 195, in __call__
    parser.print_help(file=fstr)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 2344, in print_help
    self._print_message(self.format_help(), file)
  File "/home/groot/anaconda2/lib/python2.7/argparse.py", line 2358, in _print_message
    file.write(message)

**Comment by talabadi** [comment] 2020-07-07 19:57
I installed anaconda 3 (instead of anaconda2) and it solved the problem.

But now there is a different error when trying the test commands
$ python montepython/MontePython.py run -o test -p example.param -N 100
$ python montepython/MontePython.py info test/

the analysation "info" command returns:

--> Scanning file chains/test/2020-07-07_100__1.txt: Removed 0 non-markovian points, 15 points of burn-in, keep 1 steps
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/groot/codes/montepython_public-3.3/montepython/run.py", line 32, in run
    custom_command)
  File "/home/groot/codes/montepython_public-3.3/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/groot/codes/montepython_public-3.3/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/home/groot/codes/montepython_public-3.3/montepython/analyze.py", line 108, in analyze
    convergence(info)
  File "/home/groot/codes/montepython_public-3.3/montepython/analyze.py", line 284, in convergence
    spam = remove_bad_points(info)
  File "/home/groot/codes/montepython_public-3.3/montepython/analyze.py", line 1893, in remove_bad_points
    "No decently sized chain was found. " +
io_mp.AnalyzeError: 

Analyze Error:
 /|\   No decently sized chain was found. Please wait a bit to analyze this
/_o_\  folder

**Comment by brinckmann** [comment] 2020-07-08 02:48
Thank you for the report!

@schoeneberg the first error message seems to be a consequence of the Python 3 compatibility update: when running with Python 2 the code can't parse the flags -h or --help in run or info mode (I confirmed this myself). How do we fix this? The second message indicates it works when running MontePython with Python 3.

@talabedi the last error message is because you need to let the chains run for longer before it's possible to analyse them.

Best,
Thejs

**Comment by talabadi** [comment] 2020-07-08 08:48
Thank you, everything worked fine when I increased the number of steps.

Another issue I encountered with the new version is when I tried to use a specific configuration file, for example:
" montepython/MontePython.py -conf my-machine.conf -p example.param -o test "

the code seems to identify -conf as -c conf (as an input covariance matrix). Also I couldn't find the -conf option in the -h documentation, is it removed? If so, is there another way of running the code with costume .conf file or do I have to modify the default.conf file each time?

Thanks.

**Comment by brinckmann** [comment] 2020-07-08 13:09
The option is `--conf` (with two dashes) and it should be in the help info.

Best,
Thejs

**Comment by schoeneberg** [comment] 2020-09-01 11:14
> Thank you for the report!
> 
> @schoeneberg the first error message seems to be a consequence of the Python 3 compatibility update: when running with Python 2 the code can't parse the flags -h or --help in run or info mode (I confirmed this myself). How do we fix this? The second message indicates it works when running MontePython with Python 3.
> 
> @talabadi the last error message is because you need to let the chains run for longer before it's possible to analyse them.
> 
> Best,
> Thejs

Dear Thejs,

I finally found the real cause of this bug, which had nothing to do with the --help, it was a red herring.

Anyway, the fix is in line 192 of parser_mp.py, where one needs to replace
`           from io import StringIO`
with
`           # Python3 python2 compatibility code
           try:
                from StringIO import StringIO
            except ImportError:
                from io import StringIO`
Then it should work for both python2 and python3.

Cheers,
Nils Sch.

**Comment by dchooper** [comment] 2021-02-12 10:23
This bugfix is in the pipeline and will be included in the next release.

**Closed by dchooper** 2021-02-12 10:23 UTC
