### ISSUE TITLE
Conversion of NS output not possible

### ISSUE THREAD

**Issue by fkoehlin** [brinckmann/montepython_public#5] opened 2018-07-12 05:24 UTC
Hi all,

I'm usually using MultiNest (NS) as my default sampler and on a cluster I'm still working with MontePython v2.2.1. Once the NS run has finished, I use
`montepython info /path/to/my/run/NS/` 
to convert the NS output to a regular MP chain (so that I could use `montepython info /path/to/my/run/` in a second step to get all plots and files from the converted chain). 
That procedure works fine with MP v2.2.1 but updating to v2.2.2 or now v3.0.1 results in various error messages when I execute the first command to convert the NS output to a chain. 
MP v2.2.2 complains about a missing 'log.param' file in the 'NS' subfolder (which of course is one folder up as it should...) and MP v3.0.1 just doesn't find any decently sized chain in the NS subfolder (it's supposed to create it...). 
To me it seems like that somehow the `analyze.py` module has lost its capability to deal properly with the NS subfolder from v2.2.2 onwards... 

Cheers,

Fabian

**Comment by DeannaCH** [comment] 2018-08-02 09:56
Hi,
That’s very odd, I've not had a problem analysing NS runs with any of the releases. I checked again using 3.0.1, and it analyses fine for me.
If it's a problem when you do the second analyse, I would say to check if you've activated multimodal sampling. But if the problem is in the first one, I don’t know what could cause that, other than a  compiler issue (but then it would be independent of the MP version). 
Perhaps you can send us the exact error message, so we could look into it more?
Cheers,
Deanna

**Comment by dchooper** [comment] 2021-02-10 09:51
Closing this issue due to lack of further input. 

Solution for this problem (reported in #50 ): When analysing, remove the trailing slash (i.e. `montepython info /path/to/my/run/NS`).

**Closed by dchooper** 2021-02-10 09:51 UTC
